name: Verify CHANGELOG Updated

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  call-changelog-check:
    uses: SchoutenEnZn/.github/.github/workflow-templates/verifyChangelog.yaml@main
